//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _57blocks.Logic.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pokemon
    {
        public decimal PokemonId { get; set; }
        public Nullable<decimal> UserloginId { get; set; }
        public string Name { get; set; }
        public string TypePrincipal { get; set; }
        public string TypeAlternate { get; set; }
        public Nullable<int> Level { get; set; }
        public Nullable<decimal> PC { get; set; }
    
        public virtual UserLogin UserLogin { get; set; }
    }
}
